create table tbl_storage
(
id int generated by default as identity,
name varchar(50) not null,
price float(8) not null,
type varchar(50) not null,
number int not null,
makeTime timestamp not null,
useDay int not null
);

insert into tbl_storage values(default,'耐克球鞋',12.21,'服装',12,'2038-8-9 12:23:12',30);
insert into tbl_storage values(default,'电冰箱Y型',3000,'电器',65,'2028-8-9 8:0:12',9999);
insert into tbl_storage values(default,'牙刷',5,'日用品',65,'2008-8-9 8:10:12',1);